name: Language Server Runtime CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Sync Code
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Build
              run: |
                  npm ci
                  npm run check:formatting
                  npm run compile
            - name: Test
              run: |
                  npm run test
    test-windows:
        name: Test (Windows)
        runs-on: windows-latest
        steps:
            - name: Sync Code
              uses: actions/checkout@v4
            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Build
              run: |
                  npm ci
                  npm run compile
            - name: Test
              run: |
                  npm run test
