name: Chat Types PR Validation

on:
  workflow_dispatch:  # Allows manual triggering
  pull_request:
    branches:
      - feature/flareProtocolCodeGen
    paths:
      - 'types/codegen/schemas/chatTypes.json'

jobs:
  validate-pr:
    name: Validate PR with chatTypes.json changes
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          #should we cache: 'npm'

      - name: Install dependencies
        working-directory: types/codegen
        run: npm ci

      - name: Generate types
        working-directory: types/codegen
        run: npm run generate

      - name: Build TypeScript
        working-directory: types/codegen/generated/typescript
        run: |
          npm ci
          npm run build

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          #should we cache: 'gradle'

      - name: Build Java
        working-directory: types/codegen/generated/java
        run: ./gradlew build