name: PR Message

on:
  pull_request:
    types: [opened]

jobs:
  message:
    runs-on: ubuntu-latest
    steps:
      - name: Post PR message
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Once this PR is merged and the language-server-runtime package is published, please ensure the corresponding version that contains this commit is updated in language-servers too!'
            })